-- Extra columns to match the UI
alter table public.memories add column if not exists when_label text;
alter table public.insights add column if not exists when_label text;
alter table public.insights add column if not exists at_label text;
alter table public.connectors add column if not exists scopes text[];
alter table public.connectors add column if not exists official boolean not null default false;
alter table public.connectors add column if not exists last_sync_label text;
alter table public.messages add column if not exists at_label text;

create or replace function public.seed_workspace(ws uuid, uid uuid)
returns void language plpgsql security definer set search_path=public as $fn$
declare conv_design uuid;
begin
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'Oliver now leads design — he moved off the backend team last month.', 'Announced in #engineering; he is running the design work for the team rather than backend development. Reports still route through the platform pod for hand-off.', 'Oliver', 'Role', 'stated', null, 'slack', 'Slack · #engineering', 'Priya', '6 days ago', 0.94, 'backend developer', 'design lead', 'updated 6 days ago');
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'Prefers async standups; finds daily live standups draining.', 'Wants written updates in the morning and a short live sync only twice a week.', 'You', 'Working style', 'stated', null, 'chat', 'Chat', 'You', '2 weeks ago', 0.88, null, null, '2 weeks ago');
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'Tends to do focused work in the late evening rather than the morning.', 'Message and commit timestamps cluster between 9pm and 1am across the last six weeks.', 'You', 'Working style', 'inferred', 'from 14 signals', 'chat', 'Anant''s inference', null, null, 0.62, null, null, 'noticed over time');
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'Coordinates frequently with the Thornbury account team.', 'A recurring thread of scheduling, scope, and delivery messages over the last quarter.', 'You', 'Relationships', 'aggregated', '31 messages', 'gmail', 'Gmail', null, null, 0.71, null, null, 'pattern · this quarter');
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'Grace joined the platform pod as a senior engineer this week.', 'Start date confirmed; needs repo access and an intro to the Thornbury account.', 'Grace', 'Role', 'stated', null, 'slack', 'Slack · #team-platform', 'You', '3 days ago', 0.96, null, null, '3 days ago');
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'Q3 launch is targeted for the second week of September.', 'Date discussed in the roadmap review; not yet locked pending security sign-off.', 'Q3 launch', 'Project', 'stated', null, 'notion', 'Notion · Roadmap', null, '1 week ago', 0.79, null, null, '1 week ago');
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'The team tracks delivery work in Linear, not Jira.', null, 'Team', 'Tooling', 'aggregated', '48 issues', 'linear', 'Linear', null, null, 0.83, null, null, 'pattern · ongoing');
insert into public.memories (workspace_id, owner_id, scope, fact, detail, subject, category, provenance, provenance_note, source_kind, source_label, source_speaker, source_when, confidence, superseded_from, superseded_to, when_label) values (ws, uid, 'shared', 'A security review must clear before any external launch.', 'Raised as a hard gate in the roadmap review; owned by the platform pod.', 'Process', 'Policy', 'stated', null, 'gmail', 'Gmail', 'Dara', '9 days ago', 0.9, null, null, '9 days ago');
insert into public.insights (workspace_id, kind, title, body, provenance, provenance_note, source_kind, source_label, confidence, when_label, at_label) values (ws, 'connection', 'Oliver and Grace will likely need a hand-off', 'Oliver moved to design and Grace just joined the pod he left. I noticed nobody has been named to bridge the backend work between them.', 'inferred', 'links 2 memories', 'slack', 'Slack · #engineering', 0.58, 'noticed today', '9:42am');
insert into public.insights (workspace_id, kind, title, body, provenance, provenance_note, source_kind, source_label, confidence, when_label, at_label) values (ws, 'pattern', 'Morning meetings sit against your focus hours', 'Your focused work clusters late in the evening, yet most invitations land before 11am. It may be worth protecting mornings.', 'aggregated', 'over 6 weeks', 'calendar', 'Calendar', 0.64, 'noticed this week', null);
insert into public.insights (workspace_id, kind, title, body, provenance, provenance_note, source_kind, source_label, confidence, when_label, at_label) values (ws, 'contradiction', 'Two launch dates are in play', 'The roadmap note says the second week of September, but a recent email to Thornbury promised late August. I kept both and flagged the conflict rather than choosing.', 'inferred', 'resolved to a flag', 'notion', 'Notion · Roadmap', 0.7, 'noticed 2 days ago', null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'slack', 'Slack', 'Messaging', 'available', 0, null, array['Read channels you are in','Read message history'], false, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'gmail', 'Gmail', 'Email', 'available', 0, null, array['Read messages','Read labels'], false, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'outlook', 'Outlook', 'Email', 'available', 0, null, null, false, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'drive', 'Google Drive', 'Documents', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'notion', 'Notion', 'Documents', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'calendar', 'Google Calendar', 'Calendar', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'linear', 'Linear', 'Tasks', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'github', 'GitHub', 'Code', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'teams', 'Teams', 'Messaging', 'available', 0, null, null, false, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'fireflies', 'Fireflies', 'Transcripts', 'available', 0, null, null, false, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'calendly', 'Calendly', 'Scheduling', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'zoom', 'Zoom', 'Meetings', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'meet', 'Google Meet', 'Meetings', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'dropbox', 'Dropbox', 'Documents', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'figma', 'Figma', 'Design', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'jira', 'Jira', 'Tasks', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'asana', 'Asana', 'Tasks', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'confluence', 'Confluence', 'Documents', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'trello', 'Trello', 'Tasks', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'hubspot', 'HubSpot', 'CRM', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'salesforce', 'Salesforce', 'CRM', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'discord', 'Discord', 'Messaging', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'telegram', 'Telegram', 'Messaging', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'whatsapp', 'WhatsApp Business', 'Messaging', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'messenger', 'Messenger', 'Messaging', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'wechat', 'WeChat', 'Messaging', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'signal', 'Signal', 'Messaging', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'box', 'Box', 'Documents', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'onedrive', 'OneDrive', 'Documents', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'gdocs', 'Google Docs', 'Documents', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'evernote', 'Evernote', 'Notes', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'clickup', 'ClickUp', 'Tasks', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'monday', 'monday.com', 'Tasks', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'todoist', 'Todoist', 'Tasks', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'airtable', 'Airtable', 'Databases', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'zendesk', 'Zendesk', 'Support', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'intercom', 'Intercom', 'Support', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'zoho', 'Zoho CRM', 'CRM', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'pipedrive', 'Pipedrive', 'CRM', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'gitlab', 'GitLab', 'Code', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'bitbucket', 'Bitbucket', 'Code', 'available', 0, null, null, true, null);
insert into public.connectors (workspace_id, key, name, category, status, items, items_target, scopes, official, last_sync_label) values (ws, 'loom', 'Loom', 'Meetings', 'available', 0, null, null, true, null);
end $fn$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare ws uuid;
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)), new.email)
  on conflict (id) do nothing;
  insert into public.workspaces (name, owner_id)
  values (coalesce(new.raw_user_meta_data ->> 'name', 'My') || '''s workspace', new.id)
  returning id into ws;
  insert into public.workspace_members (workspace_id, user_id, role) values (ws, new.id, 'admin');
  perform public.seed_workspace(ws, new.id);
  return new;
end $$;